package util;

public interface View {
	
	int HOME = 9;  //비회원 로그인 화면
	int LOGIN_PAGE = 1; //로그인, 회원가입 선택화면
	int LOGIN = 11;//로그인 화면
	int JOIN = 12;// 회원가입
	int MAIN = 111;//회원 로그인 화면
	int MYPAGE = 118;// 마이페이지
	int BUYPAGE = 10;
	int BUYCOUPON = 101;
	int BUYSUBSCRIBE = 102;
	int BUYMUSIC = 103; 
	int MYPAGE_UPDATESEL = 1181; //마이페이지 수정화면
	int MYPAGE_PWDUPDATE = 11811; //마이페이지에서 비밀번호 수정
	int MYPAGE_ADDRUPDATE = 11812; //마이페이지에서 주소 수정
	int MYPAGE_CARDNOUPDATE = 11813; //마이페이지에서 카드번호 수정수정
	int BOARD_LIST = 3; 
	int BOARD_INSERT = 31;
	int BOARD_READ = 32;
	int BOARD_UPDATE = 33;
	int BOARD_DELETE = 34;
	int MUSIC_PLAY = 35;  //음악플레이
	int MUSIC_COMMENT = 351; //음악 댓글
	int MUSIC_SEARCH =36; //음악검색
	int MUSIC_CHART =37;   //인기차트
	int MUSIC_RECENTCHART= 38; //최신차트
	int MUSIC_RECOMCHART =39; //추천차트
	int MUSIC_ADDMYLIST = 40; //내 음악 넣기
	int MUSIC_MYLIST = 41; // 내 음악리스트
	int MUSIC_MYPLAYMAIN = 411; //내 음악 메인
	int MUSIC_MYPLAYMETHOD = 4111; //내 음악 실행
	int MUSIC_NOMEMPLAY = 5464;
	int MUSIC_NOSUBPLAY = 2526;
	int MUSIC_NOCOUPLAY = 6543;
	int MUSIC_BUYLISTPLAY =412 ; 
	int NOTICEBOARD = 5;// 공지사항메인 
	int NOTICECONTENT = 51;// 공지 조회
	int NOTICEADD = 52;// 공지 추가
	int QBOARD = 6;// 문의 화면 메인
	int FAQBOARD = 61;//FAQ 화면 메인
	int FAQANSWER = 611;//FAQ 조회
	int FAQADD = 612;//FAQ 추가
	int Q = 62;//1:1 문의화면 메인
	int QONE =621;// 1:1문의 
	int QANSWER = 622;// 1:1 답변조회
	int QONEADMIN =63;// 1:1 관리자
	int QADMINANSWER = 631;// 1:1 관리자 답변등록 
	int ADMINMAIN = 82; // 관리자 페이지
	int ADMINMEMBER = 821; //관리자 회원정보 관리
	int AMEMBERALL = 8211; //전체 회원 조회
	int AMEMBERSEARCH = 8212; //회원 검색
	int IDSEARCH = 82121; // 아이디 겁색
	int NAMESEARCH = 82122; //이름 검색
	int ADMININCOME = 822; //수입 확인
	int DAYINCOME = 8221; //일별 수입 조회
	int ADMINMUSIC = 823; //음악 정보 관리
	int ADMINMSELECT = 8231; //음악 상세정보
	int ADMINMMOD = 82311; // 음악 정보 수정
	int ADMINMADD = 8232;// 음악 추가
	int ADMINCOU = 824; //쿠폰 정보 관리
	int ADMINCOUSELECT = 8241; //쿠폰 조회
	int ADMINCOUADD = 8242; //쿠폰 등록
	int ADMINSUB = 825; //구독권 관리
	int ADMINSUBSELECT = 8251; //구독권 조회 
	int ADMINSUBADD = 8252; //구독권 등록 
	int NOMEMPLAY = 12345;

}
